version: '3'

services:
  livecodexp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped